---
functional:
  - Регистрация через Github.
  - Регистрация через Discord.
  - Возможность играть вдвоем по сети.
  - Возможность выбрать один из языков программирования.
  - Возможность игры в реальном времени.
  - Общение в чате с противником и зрителями.
  - Возможность делать ссылку на игру.
  - Возможность вступить в открытую игру.
  - Возможность в качестве зрителя понаблюдать за открытой игрой.
  - Возможность добавлять новые задачи для игры через Github.
  - Возможность играть с ботом.
  - Возможность смотреть рейтинги.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - При смене языка на русский все меню должно переводиться на русский язык.
